### ISSUE TITLE
File .env esposti

### ISSUE THREAD

**Issue by merklefruit** [buildo/trovamascherine.org#2]
Ragazzi ho aperto la repo guardando il vostro video su youtube, non so se sia intenzionale ma sono visibili i .env di react e il config in /scripts/local-env/config/envfile-base
e forse altri, questi li ho trovati sfogliando la repo per 2 minuti.

**Comment by giogonzo** [comment]
Ciao @nicolas-racchi e grazie per il report!

Salvo errori, i file esposti non contengono veri "secrets": i due esempi che porti contengono informazioni pubbliche, o che comunque già sono incluse per necessità nel bundle JS che viene scaricato dal browser, e quindi facilmente accessibili. Quindi si, quei casi sono intenzionali.

**Comment by merklefruit** [comment]
Bene, meglio così! Sono paranoico 😅😁

**Comment by gabro** [comment]
Anche noi 😅 grazie comunque del report!
